version: '3.7'
services:
    nginx:
      container_name: nginx
      image: nginx:latest
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - flask-app

    flask-app:
      build:
        context: ./
        dockerfile: dockerfile
      environment: 
        - MY_SQL_USER=${MY_SQL_USER}
        - MY_SQL_PASS=${MY_SQL_PASS}
        - MY_SQL_HOST=${MY_SQL_HOST}
        - MY_SQL_DB=${MY_SQL_DB}
        - SECRET_KEY=${KEY}
        - MY_SQL_DB_TEST=${MY_SQL_DB_TEST} 

